BAT: 10
BLAZE: 10
CAVE_SPIDER: 10
CHICKEN: 10
COW: 10
CREEPER: 10
DONKEY: 10
ELDER_GUARDIAN: 10
ENDERMAN: 10
ENDERMITE: 10
ENDER_DRAGON: 10
EVOKER: 10
GHAST: 10
GIANT: 10
GUARDIAN: 10
HORSE: 10
HUSK: 10
IRON_GOLEM: 10
LLAMA: 10
MAGMA_CUBE: 10
MULE: 10
MUSHROOM_COW: 10
OCELOT: 10
PIG: 10
PIG_ZOMBIE: 10
PLAYER: 10
POLAR_BEAR: 10
RABBIT: 10
SHEEP: 10
SHULKER: 10
SILVERFISH: 10
SKELETON: 10
SKELETON_HORSE: 10
SLIME: 10
SNOWMAN: 10
SPIDER: 10
SQUID: 10
STRAY: 10
VEX: 10
VILLAGER: 10
VINDICATOR: 10
WITCH: 10
WITHER: 10
WITHER_SKELETON: 10
WOLF: 10
ZOMBIE: 10
ZOMBIE_HORSE: 10
ZOMBIE_VILLAGER: 10